### ISSUE TITLE
`module(sourceReader: SourceReader)`  is not available when using only `chasm` dependency

### ISSUE THREAD

**Issue by illarionov** [CharlieTap/chasm#24]
Function [module(sourceReader: SourceReader)](https://github.com/CharlieTap/chasm/blob/690bd952040645149b254a87ccbb5e32c0cbe708/chasm/src/commonMain/kotlin/io/github/charlietap/chasm/embedding/Module.kt#L15)  is part of the public API, but the SourceReader class is currently located in the `decoder` module, which is added as an "implementation" dependency rather than "api". 
As a result, to use this function, you need to also add the `io.github.charlietap.chasm:decoder` dependency in your project.

Given that this function may be useful for processing large files and has an interface similar to *kotlinx.io.Source* or *okio.BufferedSource*, I believe it should be included in the public API.

To fix this issue, the decoder module should be added as an "api" dependency, or alternatively, the `SourceReader` interface could be moved to some other common module.

**Comment by CharlieTap** [comment]
Ah this has been messed up whilst refactoring, I'm in the process of releasing 0.9 now and I'll likely look to get this in 0.9.1 in the next couple of weeks, alongside some actual integration tests

**Comment by CharlieTap** [comment]
Hey @illarionov, 0.9.1 has just been released and it reintroduces the streaming decoder, this time round its a type which exists outside of chasm's internal runtime. 

```kotlin
io.github.charlietap.chasm.stream.SourceReader
```
